### ISSUE TITLE
picture in doc 

### ISSUE THREAD

**Issue by John-peng** [asposemarketplace/Aspose_for_Apache_POI#1]
thx~but in your  code "List<Picture> pics = doc.getPicturesTable().getAllPictures();" can not get all pictures in documnet,can you tell why?

**Comment by shoaibkhan-aspose** [comment]
Thanks Walkinger for getting in touch with Aspose.
I think, you are mentioning the code from the following link and more specifically from **Apache POI** section:
https://github.com/asposemarketplace/Aspose_for_Apache_POI/wiki/Extract-Images-from-Word-Document
Although you are using the code from Apache POI section and not from Aspose section. However, the above example runs fine. You can download the running example from 
**CodePlex:** https://asposeapachepoi.codeplex.com/downloads/get/857809
**Github:** https://github.com/asposemarketplace/Aspose_for_Apache_POI/releases/download/Words-vs-WP-1.1/Extract.Images.Aspose.Words.vs.Apache.POI.WP.zip

Please point me to the exact link if you meant some other example so I could reproduce the issue.

**Comment by John-peng** [comment]
I am so sorry, Aspose. 
my problem is caused by the low-version of poi Jars,while i ignored ,your whole demo runs fine.
In my project,poi-scratchpad-3.10-FINAL.jar cause the issue ：Not all documents have all the images concatenated in the data stream although MS claims so.‍
while,your demo poi-scratchpad-3.11-beta2.jar solve my issue perfectly.
Apologize again,and good luck for you!‍

------------------ 原始邮件 ------------------
发件人: "shoaibkhan-aspose";notifications@github.com;
发送时间: 2014年8月26日(星期二) 晚上7:06
收件人: "asposemarketplace/Aspose_for_Apache_POI"Aspose_for_Apache_POI@noreply.github.com; 
抄送: "Inspiration"1198091280@qq.com; 
主题: Re: [Aspose_for_Apache_POI] picture in doc (#1)

Thanks Walkinger for getting in touch with Aspose.
 I think, you are mentioning the code from the following link and more specifically from Apache POI section:
https://github.com/asposemarketplace/Aspose_for_Apache_POI/wiki/Extract-Images-from-Word-Document
 Although you are using the code from Apache POI section and not from Aspose section. However, the above example runs fine. You can download the running example from 
CodePlex: https://asposeapachepoi.codeplex.com/downloads/get/857809
Github: https://github.com/asposemarketplace/Aspose_for_Apache_POI/releases/download/Words-vs-WP-1.1/Extract.Images.Aspose.Words.vs.Apache.POI.WP.zip

Please point me to the exact link if you meant some other example so I could reproduce the issue.
